# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      shiki:
        patterns:
          - 'shiki'
          - '@shikijs/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      commitlint:
        patterns:
          - '@commitlint/*'
      next:
        patterns:
          - 'next'
          - '@next/*'
          - 'eslint-config-next'
      qwik:
        patterns:
          - '@builder.io/qwik'
          - '@builder.io/qwik-*'
          - 'eslint-plugin-qwik'
      remix:
        patterns:
          - '@remix-run/*'
      fumadocs:
        patterns:
          - '@fumadocs/*'
          - 'fumadocs-*'
      react-router:
        patterns:
          - 'react-router'
          - '@react-router/*'
          - 'react-router-devtools'
